name: in-orbit-backend-model

services:
  pg:
    image: bitnami/postgresql
    ports:
      - '5432:5432'
    environment:
     - POSTGRES_USER=docker
     - POSTGRES_PASSWORD=docker
     - POSTGRES_DB=inorbitbackendmodel
     - POSTGRESQL_POSTGRES_PASSWORD=docker
    volumes:
     - ./docker:/docker-entrypoint-initdb.d